name: Release

on:
  release:
    types: [created]

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: sed -i -e 's/"@mpetuska\/application.env"/"application.env"/g' package.json
    - run: yarn
    - run: yarn npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}  
  github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: sed -i -e 's/"application.env"/"@mpetuska\/application.env"/g' package.json
    - run: yarn
    - run: yarn npm publish
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}